package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idAddress;
     private String no;
     private String street;
     private String add1;
     private String add2;
     private String province;
     private String country;
     private Set<UserHasAddress> userHasAddresses = new HashSet<UserHasAddress>(0);

    public Address() {
    }

    public Address(String no, String street, String add1, String add2, String province, String country, Set<UserHasAddress> userHasAddresses) {
       this.no = no;
       this.street = street;
       this.add1 = add1;
       this.add2 = add2;
       this.province = province;
       this.country = country;
       this.userHasAddresses = userHasAddresses;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getAdd1() {
        return this.add1;
    }
    
    public void setAdd1(String add1) {
        this.add1 = add1;
    }
    public String getAdd2() {
        return this.add2;
    }
    
    public void setAdd2(String add2) {
        this.add2 = add2;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<UserHasAddress> getUserHasAddresses() {
        return this.userHasAddresses;
    }
    
    public void setUserHasAddresses(Set<UserHasAddress> userHasAddresses) {
        this.userHasAddresses = userHasAddresses;
    }




}


