package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * CartHasProduct generated by hbm2java
 */
public class CartHasProduct  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private Product product;
     private Integer quantity;

    public CartHasProduct() {
    }

	
    public CartHasProduct(Cart cart, Product product) {
        this.cart = cart;
        this.product = product;
    }
    public CartHasProduct(Cart cart, Product product, Integer quantity) {
       this.cart = cart;
       this.product = product;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


