package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Set<CartHasProduct> cartHasProducts = new HashSet<CartHasProduct>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Set<CartHasProduct> cartHasProducts) {
       this.user = user;
       this.cartHasProducts = cartHasProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<CartHasProduct> getCartHasProducts() {
        return this.cartHasProducts;
    }
    
    public void setCartHasProducts(Set<CartHasProduct> cartHasProducts) {
        this.cartHasProducts = cartHasProducts;
    }




}


