package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * Count generated by hbm2java
 */
public class Count  implements java.io.Serializable {


     private Integer idCount;
     private Integer itemsSold;
     private Integer totalLikes;
     private Integer totalVisitors;

    public Count() {
    }

    public Count(Integer itemsSold, Integer totalLikes, Integer totalVisitors) {
       this.itemsSold = itemsSold;
       this.totalLikes = totalLikes;
       this.totalVisitors = totalVisitors;
    }
   
    public Integer getIdCount() {
        return this.idCount;
    }
    
    public void setIdCount(Integer idCount) {
        this.idCount = idCount;
    }
    public Integer getItemsSold() {
        return this.itemsSold;
    }
    
    public void setItemsSold(Integer itemsSold) {
        this.itemsSold = itemsSold;
    }
    public Integer getTotalLikes() {
        return this.totalLikes;
    }
    
    public void setTotalLikes(Integer totalLikes) {
        this.totalLikes = totalLikes;
    }
    public Integer getTotalVisitors() {
        return this.totalVisitors;
    }
    
    public void setTotalVisitors(Integer totalVisitors) {
        this.totalVisitors = totalVisitors;
    }




}


