package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * Div generated by hbm2java
 */
public class Div  implements java.io.Serializable {


     private Integer idDiv;
     private String where;
     private String status;
     private String content;

    public Div() {
    }

    public Div(String where, String status, String content) {
       this.where = where;
       this.status = status;
       this.content = content;
    }
   
    public Integer getIdDiv() {
        return this.idDiv;
    }
    
    public void setIdDiv(Integer idDiv) {
        this.idDiv = idDiv;
    }
    public String getWhere() {
        return this.where;
    }
    
    public void setWhere(String where) {
        this.where = where;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


