package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * Img generated by hbm2java
 */
public class Img  implements java.io.Serializable {


     private Integer idImg;
     private Product product;
     private String url1;
     private String url2;
     private String url3;
     private String url4;
     private String url5;

    public Img() {
    }

	
    public Img(Product product) {
        this.product = product;
    }
    public Img(Product product, String url1, String url2, String url3, String url4, String url5) {
       this.product = product;
       this.url1 = url1;
       this.url2 = url2;
       this.url3 = url3;
       this.url4 = url4;
       this.url5 = url5;
    }
   
    public Integer getIdImg() {
        return this.idImg;
    }
    
    public void setIdImg(Integer idImg) {
        this.idImg = idImg;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getUrl1() {
        return this.url1;
    }
    
    public void setUrl1(String url1) {
        this.url1 = url1;
    }
    public String getUrl2() {
        return this.url2;
    }
    
    public void setUrl2(String url2) {
        this.url2 = url2;
    }
    public String getUrl3() {
        return this.url3;
    }
    
    public void setUrl3(String url3) {
        this.url3 = url3;
    }
    public String getUrl4() {
        return this.url4;
    }
    
    public void setUrl4(String url4) {
        this.url4 = url4;
    }
    public String getUrl5() {
        return this.url5;
    }
    
    public void setUrl5(String url5) {
        this.url5 = url5;
    }




}


