package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer idInterfaces;
     private String uri;
     private String displayName;
     private Set<Privilages> privilageses = new HashSet<Privilages>(0);

    public Interfaces() {
    }

    public Interfaces(String uri, String displayName, Set<Privilages> privilageses) {
       this.uri = uri;
       this.displayName = displayName;
       this.privilageses = privilageses;
    }
   
    public Integer getIdInterfaces() {
        return this.idInterfaces;
    }
    
    public void setIdInterfaces(Integer idInterfaces) {
        this.idInterfaces = idInterfaces;
    }
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set<Privilages> getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set<Privilages> privilageses) {
        this.privilageses = privilageses;
    }




}


