package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date date;
     private Double total;
     private Integer status;
     private Set<InvoiceHasProduct> invoiceHasProducts = new HashSet<InvoiceHasProduct>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Date date, Double total, Integer status, Set<InvoiceHasProduct> invoiceHasProducts) {
       this.user = user;
       this.date = date;
       this.total = total;
       this.status = status;
       this.invoiceHasProducts = invoiceHasProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<InvoiceHasProduct> getInvoiceHasProducts() {
        return this.invoiceHasProducts;
    }
    
    public void setInvoiceHasProducts(Set<InvoiceHasProduct> invoiceHasProducts) {
        this.invoiceHasProducts = invoiceHasProducts;
    }




}


