package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * InvoiceHasProduct generated by hbm2java
 */
public class InvoiceHasProduct  implements java.io.Serializable {


     private Integer id;
     private Invoice invoice;
     private Product product;
     private Integer quantity;

    public InvoiceHasProduct() {
    }

	
    public InvoiceHasProduct(Invoice invoice, Product product) {
        this.invoice = invoice;
        this.product = product;
    }
    public InvoiceHasProduct(Invoice invoice, Product product, Integer quantity) {
       this.invoice = invoice;
       this.product = product;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


