package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * Privilages generated by hbm2java
 */
public class Privilages  implements java.io.Serializable {


     private Integer idPrivilages;
     private Interfaces interfaces;
     private UserType userType;

    public Privilages() {
    }

    public Privilages(Interfaces interfaces, UserType userType) {
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public Integer getIdPrivilages() {
        return this.idPrivilages;
    }
    
    public void setIdPrivilages(Integer idPrivilages) {
        this.idPrivilages = idPrivilages;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


