package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * ProductHasStone generated by hbm2java
 */
public class ProductHasStone  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Purity purity;
     private Stone stone;
     private Weight weight;
     private Integer count;

    public ProductHasStone() {
    }

	
    public ProductHasStone(Product product, Purity purity, Stone stone, Weight weight) {
        this.product = product;
        this.purity = purity;
        this.stone = stone;
        this.weight = weight;
    }
    public ProductHasStone(Product product, Purity purity, Stone stone, Weight weight, Integer count) {
       this.product = product;
       this.purity = purity;
       this.stone = stone;
       this.weight = weight;
       this.count = count;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Purity getPurity() {
        return this.purity;
    }
    
    public void setPurity(Purity purity) {
        this.purity = purity;
    }
    public Stone getStone() {
        return this.stone;
    }
    
    public void setStone(Stone stone) {
        this.stone = stone;
    }
    public Weight getWeight() {
        return this.weight;
    }
    
    public void setWeight(Weight weight) {
        this.weight = weight;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }




}


