package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Purity generated by hbm2java
 */
public class Purity  implements java.io.Serializable {


     private Integer id;
     private Puritymesurement puritymesurement;
     private String value;
     private Set<ProductHasStone> productHasStones = new HashSet<ProductHasStone>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Purity() {
    }

	
    public Purity(Puritymesurement puritymesurement) {
        this.puritymesurement = puritymesurement;
    }
    public Purity(Puritymesurement puritymesurement, String value, Set<ProductHasStone> productHasStones, Set<Product> products) {
       this.puritymesurement = puritymesurement;
       this.value = value;
       this.productHasStones = productHasStones;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Puritymesurement getPuritymesurement() {
        return this.puritymesurement;
    }
    
    public void setPuritymesurement(Puritymesurement puritymesurement) {
        this.puritymesurement = puritymesurement;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set<ProductHasStone> getProductHasStones() {
        return this.productHasStones;
    }
    
    public void setProductHasStones(Set<ProductHasStone> productHasStones) {
        this.productHasStones = productHasStones;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


