package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * Slideimages generated by hbm2java
 */
public class Slideimages  implements java.io.Serializable {


     private Integer id;
     private String img;

    public Slideimages() {
    }

    public Slideimages(String img) {
       this.img = img;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }




}


