package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stone generated by hbm2java
 */
public class Stone  implements java.io.Serializable {


     private Integer id;
     private String stone;
     private String color;
     private String shape;
     private String description;
     private Set<ProductHasStone> productHasStones = new HashSet<ProductHasStone>(0);

    public Stone() {
    }

    public Stone(String stone, String color, String shape, String description, Set<ProductHasStone> productHasStones) {
       this.stone = stone;
       this.color = color;
       this.shape = shape;
       this.description = description;
       this.productHasStones = productHasStones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStone() {
        return this.stone;
    }
    
    public void setStone(String stone) {
        this.stone = stone;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getShape() {
        return this.shape;
    }
    
    public void setShape(String shape) {
        this.shape = shape;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<ProductHasStone> getProductHasStones() {
        return this.productHasStones;
    }
    
    public void setProductHasStones(Set<ProductHasStone> productHasStones) {
        this.productHasStones = productHasStones;
    }




}


