package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1



/**
 * UserHasAddress generated by hbm2java
 */
public class UserHasAddress  implements java.io.Serializable {


     private Integer id;
     private Address address;
     private User user;

    public UserHasAddress() {
    }

    public UserHasAddress(Address address, User user) {
       this.address = address;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


