package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer idUserType;
     private String type;
     private Set<User> users = new HashSet<User>(0);
     private Set<Privilages> privilageses = new HashSet<Privilages>(0);

    public UserType() {
    }

    public UserType(String type, Set<User> users, Set<Privilages> privilageses) {
       this.type = type;
       this.users = users;
       this.privilageses = privilageses;
    }
   
    public Integer getIdUserType() {
        return this.idUserType;
    }
    
    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Privilages> getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set<Privilages> privilageses) {
        this.privilageses = privilageses;
    }




}


