package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private UserType userType;
     private String fname;
     private String lname;
     private Integer nic;
     private Integer tp1;
     private Integer tp2;
     private String img;
     private String status;
     private String password;
     private String backupPin;
     private Integer wrongCount;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private Set<Watchlist> watchlists = new HashSet<Watchlist>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<UserHasAddress> userHasAddresses = new HashSet<UserHasAddress>(0);

    public User() {
    }

	
    public User(String email, UserType userType) {
        this.email = email;
        this.userType = userType;
    }
    public User(String email, UserType userType, String fname, String lname, Integer nic, Integer tp1, Integer tp2, String img, String status, String password, String backupPin, Integer wrongCount, Set<Review> reviews, Set<Cart> carts, Set<UserLogin> userLogins, Set<Watchlist> watchlists, Set<Invoice> invoices, Set<UserHasAddress> userHasAddresses) {
       this.email = email;
       this.userType = userType;
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.tp1 = tp1;
       this.tp2 = tp2;
       this.img = img;
       this.status = status;
       this.password = password;
       this.backupPin = backupPin;
       this.wrongCount = wrongCount;
       this.reviews = reviews;
       this.carts = carts;
       this.userLogins = userLogins;
       this.watchlists = watchlists;
       this.invoices = invoices;
       this.userHasAddresses = userHasAddresses;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Integer getNic() {
        return this.nic;
    }
    
    public void setNic(Integer nic) {
        this.nic = nic;
    }
    public Integer getTp1() {
        return this.tp1;
    }
    
    public void setTp1(Integer tp1) {
        this.tp1 = tp1;
    }
    public Integer getTp2() {
        return this.tp2;
    }
    
    public void setTp2(Integer tp2) {
        this.tp2 = tp2;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getBackupPin() {
        return this.backupPin;
    }
    
    public void setBackupPin(String backupPin) {
        this.backupPin = backupPin;
    }
    public Integer getWrongCount() {
        return this.wrongCount;
    }
    
    public void setWrongCount(Integer wrongCount) {
        this.wrongCount = wrongCount;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }
    public Set<Watchlist> getWatchlists() {
        return this.watchlists;
    }
    
    public void setWatchlists(Set<Watchlist> watchlists) {
        this.watchlists = watchlists;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<UserHasAddress> getUserHasAddresses() {
        return this.userHasAddresses;
    }
    
    public void setUserHasAddresses(Set<UserHasAddress> userHasAddresses) {
        this.userHasAddresses = userHasAddresses;
    }




}


