package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer idUserLogin;
     private User user;
     private String ipAddress;
     private Date inTime;
     private Date outTime;

    public UserLogin() {
    }

	
    public UserLogin(User user) {
        this.user = user;
    }
    public UserLogin(User user, String ipAddress, Date inTime, Date outTime) {
       this.user = user;
       this.ipAddress = ipAddress;
       this.inTime = inTime;
       this.outTime = outTime;
    }
   
    public Integer getIdUserLogin() {
        return this.idUserLogin;
    }
    
    public void setIdUserLogin(Integer idUserLogin) {
        this.idUserLogin = idUserLogin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }




}


