package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Weightmesurement generated by hbm2java
 */
public class Weightmesurement  implements java.io.Serializable {


     private Integer id;
     private String weightMesurement;
     private Set<Weight> weights = new HashSet<Weight>(0);

    public Weightmesurement() {
    }

    public Weightmesurement(String weightMesurement, Set<Weight> weights) {
       this.weightMesurement = weightMesurement;
       this.weights = weights;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getWeightMesurement() {
        return this.weightMesurement;
    }
    
    public void setWeightMesurement(String weightMesurement) {
        this.weightMesurement = weightMesurement;
    }
    public Set<Weight> getWeights() {
        return this.weights;
    }
    
    public void setWeights(Set<Weight> weights) {
        this.weights = weights;
    }




}


