package Pojos;
// Generated Jun 16, 2018 10:23:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Weight generated by hbm2java
 */
public class Weight  implements java.io.Serializable {


     private Integer id;
     private Weightmesurement weightmesurement;
     private String weight;
     private Set<Product> products = new HashSet<Product>(0);
     private Set<ProductHasStone> productHasStones = new HashSet<ProductHasStone>(0);

    public Weight() {
    }

	
    public Weight(Weightmesurement weightmesurement) {
        this.weightmesurement = weightmesurement;
    }
    public Weight(Weightmesurement weightmesurement, String weight, Set<Product> products, Set<ProductHasStone> productHasStones) {
       this.weightmesurement = weightmesurement;
       this.weight = weight;
       this.products = products;
       this.productHasStones = productHasStones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Weightmesurement getWeightmesurement() {
        return this.weightmesurement;
    }
    
    public void setWeightmesurement(Weightmesurement weightmesurement) {
        this.weightmesurement = weightmesurement;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }
    public Set<ProductHasStone> getProductHasStones() {
        return this.productHasStones;
    }
    
    public void setProductHasStones(Set<ProductHasStone> productHasStones) {
        this.productHasStones = productHasStones;
    }




}


